[tool.poetry]
name = "test-automation-task"
version = "0.1.0"
description = "UI automation project for saucedemo.com"
authors = []
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
playwright = "^1.44"
pytest-playwright = "^0.5"
pydantic-settings = "^2.3"
python-dotenv = "^1.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2"

[tool.pytest.ini_options]

addopts = "--tb=short -v"

filterwarnings = ["error::pytest.PytestUnknownMarkWarning"]

markers = [
    "smoke: fast, critical-path tests that must pass before anything else",
    "regression: full test suite, runs on every PR / nightly",
    "parametrize(argnames, argvalues): call a test function multiple times passing in different arguments in turn"
]

testpaths = ["tests"]
